name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.7"
            runs-on: ubuntu-20.04
          - python-version: "3.8"
            runs-on: ubuntu-20.04
          - python-version: "3.9"
            runs-on: ubuntu-20.04
          - python-version: "3.10"
            runs-on: ubuntu-22.04
          - python-version: "3.11"
            runs-on: ubuntu-22.04
          - python-version: "pypy-3.7"
            runs-on: ubuntu-20.04
          - python-version: "pypy-3.8"
            runs-on: ubuntu-20.04
          - python-version: "pypy-3.9"
            runs-on: ubuntu-20.04
          - python-version: "pypy-3.10"
            runs-on: ubuntu-22.04
          - python-version: "pypy-3.11"
            runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project dependencies
        run: |
          pip install --upgrade pip
          pip install codecov tox tox-gh-actions

      - name: "Debug OpenSSL version used with Python ${{ matrix.python-version }}"
        run: |
          which python
          python --version
          python -c 'import ssl; print(ssl.OPENSSL_VERSION_INFO)'

      - name: Run tests with tox
        run: tox

      - name: Run coverage
        run: codecov
